// Verify that an invalid password message is displayed when a user attempts to log in with incorrect credentials.
// Generated by VibeQA Generator

describe('Invalid Password Message Display', () => {
  const baseUrl = 'https://www.windscribe.com';

  it('should invalid password message display', () => {
    // Step 1: The homepage is loaded successfully.
    cy.visit('https://www.windscribe.com');
    
    // Step 2: Login button is visible on the homepage.
    cy.get('[data-test=login-button]', { timeout: 10000 }).should('exist');
    
    // Step 3: Login form is displayed.
    cy.get('[data-test=login-button]').click();
    
    // Step 4: Email input field is visible.
    cy.get('[data-test=email-input]', { timeout: 10000 }).should('exist');
    
    // Step 5: Email is entered into the email input field.
    cy.get('[data-test=email-input]').type('testuser@example.com');
    
    // Step 6: Password is entered into the password input field.
    cy.get('[data-test=password-input]').type('wrongpassword');
    
    // Step 7: Login attempt is made with the provided credentials.
    cy.get('[data-test=submit-button]').click();
    
    // Step 8: Error message is displayed on the screen.
    cy.get('[data-test=error-message]', { timeout: 10000 }).should('exist');
    
    // Step 9: Error message contains the text 'Invalid password'.
    cy.get('[data-test=error-message]').should('contain.text', 'Invalid password');
    
    // Step 10: Error message is visible to the user.
    cy.get('[data-test=error-message]').should('be.visible');
    
  });
});